// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/assets/headshot/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/assets/headshot/[id].get').default>>>>
    }
    '/api/authentication/delete': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/authentication/delete.delete').default>>>>
    }
    '/api/authentication/forgot': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/authentication/forgot.post').default>>>>
    }
    '/api/authentication/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/authentication/login.post').default>>>>
    }
    '/api/authentication/reset': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/authentication/reset').default>>>>
    }
    '/api/authentication/signup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/authentication/signup.post').default>>>>
    }
    '/api/briefing': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/briefing/index.get').default>>>>
    }
    '/api/campaigns': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/campaigns/index.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/campaigns/index.get').default>>>>
    }
    '/api/campaigns/save': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/campaigns/save.post').default>>>>
    }
    '/api/campaigns/toggle': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/campaigns/toggle.post').default>>>>
    }
    '/api/campaigns/vary': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/campaigns/vary.post').default>>>>
    }
    '/api/charts/lead': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/charts/lead.get').default>>>>
    }
    '/api/cron': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cron').default>>>>
    }
    '/api/documents/:id/deadline': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/documents/[id]/deadline.post').default>>>>
    }
    '/api/documents/:id/delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/documents/[id]/delete.post').default>>>>
    }
    '/api/documents/:id/read': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/documents/[id]/read.post').default>>>>
    }
    '/api/documents/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/documents/create.post').default>>>>
    }
    '/api/documents/deadlines': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/documents/deadlines.get').default>>>>
    }
    '/api/documents/diagnose': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/documents/diagnose.get').default>>>>
    }
    '/api/documents': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/documents/index.get').default>>>>
    }
    '/api/homes/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/homes/[id]/index.get').default>>>>
    }
    '/api/homes/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/homes/create.post').default>>>>
    }
    '/api/homes/delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/homes/delete.post').default>>>>
    }
    '/api/homes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/homes/index.get').default>>>>
    }
    '/api/homes/update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/homes/update.post').default>>>>
    }
    '/api/leads/:id/analyse': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leads/[id]/analyse.post').default>>>>
    }
    '/api/leads/:id/contacted': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leads/[id]/contacted.post').default>>>>
    }
    '/api/leads/:id/draft': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leads/[id]/draft.post').default>>>>
    }
    '/api/leads/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leads/[id]/index.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leads/[id]/index.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leads/[id]/index.put').default>>>>
    }
    '/api/leads/:id/schedule': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leads/[id]/schedule.post').default>>>>
    }
    '/api/leads/:id/send-message': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leads/[id]/send-message.post').default>>>>
    }
    '/api/leads/:id/send-questionnaire': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leads/[id]/send-questionnaire.post').default>>>>
    }
    '/api/leads/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leads/create.post').default>>>>
    }
    '/api/leads/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leads/import.post').default>>>>
    }
    '/api/leads': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leads/index.get').default>>>>
    }
    '/api/leads/tiers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leads/tiers.get').default>>>>
    }
    '/api/qr_code/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/qr_code/[id].get').default>>>>
    }
    '/api/qualify/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/qualify/[id].get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/qualify/[id].post').default>>>>
    }
    '/api/social/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/social/generate.post').default>>>>
    }
    '/api/social': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/social/index.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/social/index.get').default>>>>
    }
    '/api/social/save': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/social/save.post').default>>>>
    }
    '/api/social/status': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/social/status.post').default>>>>
    }
    '/api/storage-mode': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/storage-mode.get').default>>>>
    }
    '/api/stripe/subscribe': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stripe/subscribe.post').default>>>>
    }
    '/api/stripe/webhook': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stripe/webhook.post').default>>>>
    }
    '/api/test-reminder': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test-reminder.get').default>>>>
    }
    '/api/uploads/local/**:key': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/uploads/local/[...key].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/uploads/local/[...key].put').default>>>>
    }
    '/api/uploads/sign': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/uploads/sign.post').default>>>>
    }
    '/api/user/card-style': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/card-style.post').default>>>>
    }
    '/api/user/headshot': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/headshot.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/headshot.post').default>>>>
    }
    '/api/user': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/index.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/index.put').default>>>>
    }
    '/api/user/tour': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/tour.post').default>>>>
    }
    '/api/user/voice': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/voice.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/api/_auth/session': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.get').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}